# Generated by Django 3.1.1 on 2020-09-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200919_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
