# Generated by Django 3.1.1 on 2020-10-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201008_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='moderator',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
