# Generated by Django 3.1.1 on 2020-10-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
