# Generated by Django 3.1.1 on 2020-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201007_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='moderator'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_mute',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
