# Generated by Django 3.1.1 on 2020-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201007_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_ban',
            field=models.BooleanField(),
        ),
    ]
