# Generated by Django 3.1.1 on 2020-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201007_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
