# Generated by Django 3.1.1 on 2020-10-07 14:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20201007_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bans',
            new_name='Ban',
        ),
    ]
