# Generated by Django 3.1.1 on 2020-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201007_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_mute',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Ban',
        ),
    ]
