# Generated by Django 3.1.1 on 2020-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201007_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='is_ban'),
        ),
    ]
