# Generated by Django 3.1.1 on 2020-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201007_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='auth.User'),
        ),
    ]
